#!/bin/bash
echo "PLAINEDIT takes markdown, evaluates code blocks with interpreters and prints the output of those processes to a different codeblock."
# CONFIG
FILE=$1
NEW_FILE=$2
BASHLINE=
SEPARATOR='```'
SCRIPT_FILE=
FLAGS=
FLAG_HIDE_INPUT=
LANGUAGE=
SCRIPT_HIDE=
FIRST_SEPARATOR_IN_LINE=
ONLY_EXECUTED=
#set -e
# EXAMPLE
# ./plainedit "test.md" "test_out.md"
# START
echo "" > $NEW_FILE
SCRIPT_COUNTER=0

## read line by LINE
while IFS= read -r LINE; do

  # save line by line to new file:
  #FOLDER_NAME=${BRANCH//.git}

  #FLAG_HIDE_INPUT=

  FIRST_SEPARATOR_IN_LINE=

  case $LINE in ${SEPARATOR}*)
     FIRST_SEPARATOR_IN_LINE=1
     LINE_CLEAN=$LINE
     FLAGS=${LINE_CLEAN##*\`}
     IFS=' ' read -r -a array <<< "$FLAGS"
     LANGUAGE="${array[0]}"
     HIDE="${array[1]}"
     HIDE_INPUT="${array[2]}"
     echo "FLAGS"
     echo "$FLAGS"
     echo "$LANGUAGE"
     echo "$HIDE"
  esac



  # if line started with: ```bash
  if [[ ! -z "$FIRST_SEPARATOR_IN_LINE" ]] && [[ ! -z "$LANGUAGE" ]] && [[ -z "$SCRIPT_HIDE" ]];
  then
      SCRIPT_LANGUAGE=$LANGUAGE
      SCRIPT_HIDE=$HIDE
      #LINE_CLEAN=${LINE//[$'\t\r\n']}
      SCRIPT_TYPE=${FLAGS}
      #echo "$LINE_CLEAN"
      #echo "${SCRIPT_TYPE}"
      ((SCRIPT_COUNTER++))
      #echo $SCRIPT_COUNTER
      SCRIPT_FILE="script/$SCRIPT_COUNTER.$SCRIPT_LANGUAGE"
      HEADER_FILE="#!/bin/${SCRIPT_LANGUAGE}"
      [[ $SCRIPT_LANGUAGE == 'php' ]] && HEADER_FILE="<?php"
      echo "$HEADER_FILE" > $SCRIPT_FILE
      BASHLINE="1"

      if [[ -z "$ONLY_EXECUTED" ]] && [[ -z "$SCRIPT_HIDE" ]];
      then
        echo "$LINE" >> $NEW_FILE
      fi

      continue
  fi


  if [[ -z "$ONLY_EXECUTED" ]] && [[ -z "$SCRIPT_HIDE" ]];
  then
    echo "$LINE" >> $NEW_FILE
  else
    echo "NOT SHOW: $LINE"
  fi

  #echo $BASHLINE

  # if line started with: ```
  if [[ $BASHLINE == "1" ]] && [[ $LINE == "${SEPARATOR}" ]];
  then
      BASHLINE=

      if [[ -z "$SCRIPT_HIDE" ]] && [[ ! -z "$ONLY_EXECUTED" ]] && [[ -z "$SCRIPT_HIDE" ]]; then
        #echo "EXECUTED: ${SCRIPT_COUNTER}.sh"
        echo "EXECUTED ${SCRIPT_LANGUAGE}:" >> $NEW_FILE
        echo "${SEPARATOR}${SCRIPT_LANGUAGE}" >> $NEW_FILE
        CMD="sh"
        [[ $SCRIPT_LANGUAGE != 'bash' ]] && CMD=$SCRIPT_LANGUAGE
        SCRIPT_CMD="./script/$SCRIPT_COUNTER.$SCRIPT_LANGUAGE"
        [[ $SCRIPT_LANGUAGE == 'php' ]] && SCRIPT_CMD="$CMD script/$SCRIPT_COUNTER.$SCRIPT_LANGUAGE"
        #EXECUTE="$CMD $SCRIPT_FILE"
        echo "$SCRIPT_CMD"
        # Redirected stderr to stdout, stdout to FILE
        { OUTPUT=$( $SCRIPT_CMD 2>>$NEW_FILE 1>&$out); } {out}>>$NEW_FILE
        #echo "" >> $NEW_FILE

        echo -e "\n$SEPARATOR" >> $NEW_FILE
        continue

      fi
      SCRIPT_HIDE=
  else

    # if $BASHLINE and NOT HIDE
    if [[ ! -z "$LANGUAGE" ]] && [[ -z "$SCRIPT_HIDE" ]];
    then
      #echo -e "$LINE"
      echo -e "$LINE" >> $SCRIPT_FILE
    fi

  fi


done < $FILE
