#!/bin/bash
echo "PLAINEDIT takes markdown, evaluates code blocks with interpreters and prints the output of those processes to a different codeblock."
# CONFIG
FILE=$1
NEW_FILE=$2
BASHLINE=

# START
echo "" > $NEW_FILE
SCRIPT_COUNTER=0

## LOOP
## read line by LINE
while read LINE
do

  echo $LINE
  # save line by line to new file:
  echo "$LINE" >> $NEW_FILE

  # if line started with: ```bash
  if [[ $LINE == '```bash' ]]; then
      echo $SCRIPT_COUNTER
      ((SCRIPT_COUNTER++))
      echo $SCRIPT_COUNTER
      echo "" > "script/$SCRIPT_COUNTER.sh"
      BASHLINE="1"
      continue
  fi

  echo $BASHLINE

  # if line started with: ```
  if [[ $BASHLINE == "1" ]] && [[ $LINE == '```' ]]; then
      BASHLINE=""
      echo "EXECUTE: ${SCRIPT_COUNTER}.sh"
      echo ' EXECUTE bash' >> $NEW_FILE
      echo '```bash' >> $NEW_FILE
      sh script/${SCRIPT_COUNTER}.sh >> $NEW_FILE
      echo '```' >> $NEW_FILE

      #sh script/${SCRIPT_COUNTER}.sh > "script_out/$SCRIPT_COUNTER.txt"
      #cat script_out/${SCRIPT_COUNTER}.txt
      #cat "script_out/$SCRIPT_COUNTER.txt" >> $NEW_FILE
      continue
  else
    # if $BASHLINE
    if [[ $BASHLINE != "" ]]; then
      echo "$LINE" >> "script/$SCRIPT_COUNTER.sh"
    fi
  fi


done < $FILE
